apiVersion: v1
kind: PersistentVolume
metadata:
  name: arnoldmongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/arnoldmongo-pv  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arnoldmongo-pvc
  namespace: arnoldmongo-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
